### ISSUE TITLE
TODO before 1.0

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-sdk#3]
SDK 1.0 is ready to be released!

The SDK should have more features than just a wrapper.

- [x] **More examples**
Currently we have only @bitcart_atomic_tipbot on telegram as an example, it is in `examples/atomic_tipbot` folder.
It should be updated to show that bitcart also easily supports lightning network.
Also if `APIManager` would be added, it would be a great example of Managers then.
We should also add more basic examples, something like hello world but in bitcart world (: 
Some things to know should be added to docs too. 

- [x] **Possibly, consider switching to httpx instead of aiohttp and requests.**
[HTTPX](https://www.python-httpx.org) has both sync and async versions, making it easier to use in our use case.
It does not have server functionality, so webhook functionality would optionally still require aiohttp or a similar library.
But aiohttp client is hard to deal with because of unclosed session hacks, which shouldn't be a problem (and it isn't in httpx).
We'll migrate to httpx when version 1.0 it's out.

- [x] #9 Stop using sync_generator.py

- [x] #4 Better exceptions
- [x] **Managers**
For example, for each new wallet you have to create a new coin instance and pass xpub to it.
For other coin, you have to use other coin class.
It is fine, but we could add a manager, with the following possible API draft:
```
from bitcart import APIManager
manager = APIManager({"BTC": ["xpub1","xpub2"], "LTC": ["xpub1","xpub2"],"GZRO": ["xpub1","xpub2"], "BCH": ["xpub1","xpub2"]})
print(manager["BTC"]["xpub1"].balance())
print(manager["BTC"]["xpub2"].balance())
print(manager["LTC"]["xpub2"].balance())
# or maybe also
print(manager.BTC.xpub1.balance())
print(manager.BTC.xpub2.balance())
print(manager.LTC.xpub2.balance())
```

- [x] **Better async support**
Also, in async version of SDK maybe something needs to be done to remove `async with Coin():`
As after this block end it will close the session and coin becomes unusable.
It is because of aiohttp session not closing automatically.
Also maybe `async for` support could be added for some methods.

- [x] **New utilities**
Each coin may have new `format_satoshis` method or whatever called which can conveniently convert coin to satoshi or whatever this coin has.
Also some other utility functions may be considered.
